name: Update security.txt PR

on:
  schedule:
    # 3 days before end of the month in July and January
    - cron: '0 0 28 7 *'
    - cron: '0 0 28 1 *'
  workflow_dispatch:

jobs:
  update_security:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python ./.github/scripts/update_security.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update security.txt expiration
          committer: OpenAQ Dev <dev@openaq.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: security-txt-update
          delete-branch: true
          title: 'security.txt renewal'
          body: |
            Update security.txt expiration
            - Updates security.txt expirate date to 6 months in the future
